### PR TITLE
Database part

### PR DESCRIPTION
**Pull request by javabackenddeveloper**
men filelar bilan ishlaydigan database yozdim

### CODE REVIEW

**Comment by beckmuradov** [comment]
zo`r

**Review by beckmuradov — APPROVED** [review]
++

**Review by ibrokhimali786 — APPROVED** [review]
Zo'r

**Review by Sardorbek870 — APPROVED** [review]
good

**Comment by Sardorbek870** [comment]
good

**Review by axrortatu — APPROVED** [review]

**Pull request merged**
