### PR TITLE
General part

### PR DESCRIPTION
**Pull request by javabackenddeveloper**

### CODE REVIEW

**Review by axrortatu — APPROVED** [review]

**Comment by beckmuradov** [comment]
Well done

**Comment by ibrokhimali786** [comment]
Maladets. Gap nes

**Review by beckmuradov — APPROVED** [review]
Good job

**Review by ibrokhimali786 — COMMENTED** [review]
Gap nes👏

**Review by ibrokhimali786 — APPROVED** [review]

**Comment by javabackenddeveloper** [comment]
General part branch was merged

**Pull request merged**
